version: "3.8"

services:
  springboot-messageService:
    container_name: message-service
    image: message-service
    build:
      context: ./
      dockerfile: DockerFile
    ports:
      - 8083:8083
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3307/PatientInfo
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: on-failure